#%RAML 1.0 DataType

type: object

properties:
   type_of_service_id:
    type: string
    required: true
   name:
    type: string
    required: false
   description:
    type: string
    required: false
   actual:
    type: boolean
    required: false
   price:
    type: string
    required: false
   service:
    type: object
    required: true
  